language: objective-c

env:
  #global:
    #- LATEST_TAG=1
  matrix:
    - VERSION=2.7.8 NUMPY=1.7.1
    - VERSION=3.3.5 NUMPY=1.7.1
    - VERSION=3.4.1 NUMPY=1.7.1
    - VERSION=3.5.0 NUMPY=1.9.3
    
install:
  - cd terryfy && git fetch && git checkout master && cd ..
  - source terryfy/travis_tools.sh
  - travis_retry get_python_environment macpython $VERSION venv
  - if [ -n "$LATEST_TAG" ]; then 
      checkout_closest_tag lensfunpy ;
    else
      cd lensfunpy ;
      git fetch ;
      git checkout -f master ;
      git log -n 1 ;
      cd .. ;
    fi
  - cd lensfunpy
  - travis_retry pip install numpy==$NUMPY
  - travis_retry pip install -r dev-requirements.txt
  - travis_retry brew update
  - travis_retry brew install --universal glib
  - brew link --force gettext
  - export CC=clang
  - export CXX=clang++
  - export CFLAGS="-arch i386 -arch x86_64"
  - export CXXFLAGS=$CFLAGS
  - export LDFLAGS=$CFLAGS
  - export ARCHFLAGS=$CFLAGS
  - python setup.py bdist_wheel
  - travis_retry pip install delocate
  - delocate-listdeps --all dist/*.whl # lists library dependencies
  - delocate-wheel --require-archs=intel dist/*.whl # copies library dependencies into wheel
  - delocate-listdeps --all dist/*.whl # verify
  - rename_wheels dist
  - pip install dist/*.whl
  - cd ..

script:
  # make sure it's working without any required libraries installed
  - brew rm glib
  - brew rm gettext
  - mkdir tmp_for_test
  - cd tmp_for_test
  - nosetests --verbosity=3 --nocapture ../lensfunpy/test
  - cd ..

after_success:
  - cd lensfunpy
  - "if [[ \"`git log -n 1 --pretty=format:'%d'`\" =~ \"tag: v\" ]]; then
       travis_retry pip install twine ;
       twine upload -u letmaik -p $PYPI_PASS dist/* ;
     fi"
