os: osx
language: generic

# use oldest available image to be as compatible as possible when producing wheels
osx_image: xcode6.4 # = OS X 10.10 

env:
  #global:
    #- LATEST_TAG=1
  matrix:
    - PYTHON_VERSION=2.7
      NUMPY_VERSION=1.7.1 # 1.7.2 has no macOS wheels
            
    - PYTHON_VERSION=3.4
      NUMPY_VERSION=1.8.*
      
    - PYTHON_VERSION=3.5
      NUMPY_VERSION=1.9.*

    - PYTHON_VERSION=3.6
      NUMPY_VERSION=1.11.*
    
install:
  - cd terryfy && git fetch && git checkout master && cd ..
  - source terryfy/travis_tools.sh
  - travis_retry get_python_environment macports $PYTHON_VERSION venv
  - if [ -n "$LATEST_TAG" ]; then 
      checkout_closest_tag lensfunpy ;
    else
      cd lensfunpy ;
      git fetch ;
      git checkout -f master ;
      git log -n 1 ;
      cd .. ;
    fi
  - cd lensfunpy
  # necessary, otherwise the lensfun submodule points to an old commit
  - git submodule update --recursive --init
  - travis_retry pip install numpy==$NUMPY_VERSION
  - travis_retry pip install -r dev-requirements.txt
  - travis_retry brew update
  - travis_retry brew install glib
  - brew link --force gettext
  - export CC=clang
  - export CXX=clang++
  - export CFLAGS="-arch x86_64"
  - export CXXFLAGS=$CFLAGS
  - export LDFLAGS=$CFLAGS
  - export ARCHFLAGS=$CFLAGS
  - python setup.py bdist_wheel
  - travis_retry pip install delocate
  - delocate-listdeps --all dist/*.whl # lists library dependencies
  - delocate-wheel --require-archs=x86_64 dist/*.whl # copies library dependencies into wheel
  - delocate-listdeps --all dist/*.whl # verify
  - pip install dist/*.whl
  - cd ..

script:
  # make sure it's working without any required libraries installed
  - brew rm glib
  - brew unlink gettext
  - mkdir tmp_for_test
  - cd tmp_for_test
  - nosetests --verbosity=3 --nocapture ../lensfunpy/test
  - cd ..

deploy:
  provider: pypi
  user: letmaik
  skip_upload_docs: true
  skip_cleanup: true
  password:
    secure: GW2vr0X3tka3QQT4MiqPIt1aJ++HxI7bwbpSBj5zURvjGQQ/IKWJp1HBVkdFD+skpnctZyLxh97SprGZXLGtcbXLTDi7u+bkzW30Mv2FR4zHFb5dWCdf5mutinZG5dCmWmxvMx0GhNGpVsxo4Y/LDt+r0tPyT6DtmDs/9B01dLs=
  on:
    tags: true
